spring.application.name=UserService
server.port=8082

spring.datasource.password=postgres
spring.datasource.username=admin
spring.datasource.url=jdbc:postgresql://localhost:5433/users_db
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver

kafka.bootstrap-servers=localhost:8761
kafka.topics.auth-created=auth_created