spring.application.name=AuthService
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=admin
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

access_token_lifetime=${ACCESS_TOKEN_LIFETIME}
secret_key=${SECRET_KEY}