spring.application.name=GatewayAPI
server.port=8080

eureka.client.service-url.defaulZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

#auth service
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://authService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/{*catchall}

#user service
spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AUTHSERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/users/{*catchall}

jwt.secret.key=${SECRET_KEY}